<a href="https://colab.research.google.com/github/ramana692/231FA04A56_MLOPS1/blob/main/cla1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

project_dir = "/content/MLOps-Feast-SkillGap"

folders = [
    "data",
    "feature_store",
    "outputs",
    "src"
]

for folder in folders:
    os.makedirs(os.path.join(project_dir, folder), exist_ok=True)

print("Project structure created successfully.")

for root, dirs, files in os.walk(project_dir):
    level = root.replace(project_dir, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

Project structure created successfully.
MLOps-Feast-SkillGap/
  feature_store/
  src/
  outputs/
  data/

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

skills = [
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "SQL",
    "HTML_CSS",
    "React",
    "NodeJS",
    "MongoDB",
    "Git",
    "Docker",
    "Kubernetes",
    "AWS",
    "Machine_Learning",
    "Data_Structures",
    "Algorithms",
    "Computer_Networks",
    "Cybersecurity",
    "Hadoop",
    "Spark"
]

curriculum_score = [
    8, 7, 8, 8, 9,
    7, 5, 5, 5, 6,
    3, 2, 3, 4, 9,
    9, 7, 4, 3, 3
]

industry_score = [
    9, 9, 8, 7, 9,
    8, 8, 8, 7, 9,
    8, 7, 8, 9, 8,
    9, 8, 8, 7, 7
]

student_proficiency = [
    7, 5, 6, 6, 7,
    5, 4, 4, 4, 6,
    3, 2, 3, 3, 7,
    7, 5, 4, 3, 3
]

industry_demand = [
    9, 9, 8, 7, 9,
    8, 8, 8, 7, 9,
    8, 7, 8, 9, 9,
    9, 8, 8, 7, 7
]

df = pd.DataFrame({
    "skill_id": [f"S{i:03d}" for i in range(1, 21)],
    "skill": skills,
    "curriculum_score": curriculum_score,
    "industry_score": industry_score,
    "student_proficiency": student_proficiency,
    "industry_demand": industry_demand
})

# Calculate skill gap
df["skill_gap"] = df["industry_score"] - df["curriculum_score"]

# Calculate proficiency gap
df["proficiency_gap"] = df["industry_demand"] - df["student_proficiency"]

# Target:
# 1 = High-priority skill gap
# 0 = Low/Moderate-priority skill gap
df["target"] = (
    (df["skill_gap"] >= 2) |
    (df["proficiency_gap"] >= 4)
).astype(int)

df

,skill_id,skill,curriculum_score,industry_score,student_proficiency,industry_demand,skill_gap,proficiency_gap,target
0,S001,Python,8,9,7,9,1,2,0
1,S002,JavaScript,7,9,5,9,2,4,1
2,S003,Java,8,8,6,8,0,2,0
3,S004,C++,8,7,6,7,-1,1,0
4,S005,SQL,9,9,7,9,0,2,0
5,S006,HTML_CSS,7,8,5,8,1,3,0
6,S007,React,5,8,4,8,3,4,1
7,S008,NodeJS,5,8,4,8,3,4,1
8,S009,MongoDB,5,7,4,7,2,3,1
9,S010,Git,6,9,6,9,3,3,1
10,S011,Docker,3,8,3,8,5,5,1
11,S012,Kubernetes,2,7,2,7,5,5,1
12,S013,AWS,3,8,3,8,5,5,1
13,S014,Machine_Learning,4,9,3,9,5,6,1
14,S015,Data_Structures,9,8,7,9,-1,2,0
15,S016,Algorithms,9,9,7,9,0,2,0
16,S017,Computer_Networks,7,8,5,8,1,3,0
17,S018,Cybersecurity,4,8,4,8,4,4,1
18,S019,Hadoop,3,7,3,7,4,4,1
19,S020,Spark,3,7,3,7,4,4,1

In [3]:
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nTarget distribution:")
print(df["target"].value_counts())

print("\nDataset:")
display(df)

Dataset shape: (20, 9)

Columns:
['skill_id', 'skill', 'curriculum_score', 'industry_score', 'student_proficiency', 'industry_demand', 'skill_gap', 'proficiency_gap', 'target']

Target distribution:
target
1    12
0     8
Name: count, dtype: int64

Dataset:

,skill_id,skill,curriculum_score,industry_score,student_proficiency,industry_demand,skill_gap,proficiency_gap,target
0,S001,Python,8,9,7,9,1,2,0
1,S002,JavaScript,7,9,5,9,2,4,1
2,S003,Java,8,8,6,8,0,2,0
3,S004,C++,8,7,6,7,-1,1,0
4,S005,SQL,9,9,7,9,0,2,0
5,S006,HTML_CSS,7,8,5,8,1,3,0
6,S007,React,5,8,4,8,3,4,1
7,S008,NodeJS,5,8,4,8,3,4,1
8,S009,MongoDB,5,7,4,7,2,3,1
9,S010,Git,6,9,6,9,3,3,1
10,S011,Docker,3,8,3,8,5,5,1
11,S012,Kubernetes,2,7,2,7,5,5,1
12,S013,AWS,3,8,3,8,5,5,1
13,S014,Machine_Learning,4,9,3,9,5,6,1
14,S015,Data_Structures,9,8,7,9,-1,2,0
15,S016,Algorithms,9,9,7,9,0,2,0
16,S017,Computer_Networks,7,8,5,8,1,3,0
17,S018,Cybersecurity,4,8,4,8,4,4,1
18,S019,Hadoop,3,7,3,7,4,4,1
19,S020,Spark,3,7,3,7,4,4,1

In [4]:
original_path = f"{project_dir}/data/original_dataset.csv"

df.to_csv(original_path, index=False)

print(f"Dataset saved to: {original_path}")

Dataset saved to: /content/MLOps-Feast-SkillGap/data/original_dataset.csv

In [5]:
import pandas as pd
import numpy as np

# Load original dataset
original_path = f"{project_dir}/data/original_dataset.csv"
df = pd.read_csv(original_path)

# Create a copy for feature engineering
feature_df = df.copy()

# Feature 1: Curriculum-Industry Gap
feature_df["skill_gap"] = (
    feature_df["industry_score"] -
    feature_df["curriculum_score"]
)

# Feature 2: Student Proficiency Gap
feature_df["proficiency_gap"] = (
    feature_df["industry_demand"] -
    feature_df["student_proficiency"]
)

# Feature 3: Industry Demand Ratio
feature_df["industry_demand_ratio"] = (
    feature_df["industry_demand"] / 10.0
)

# Feature 4: Curriculum Coverage Ratio
feature_df["curriculum_coverage_ratio"] = (
    feature_df["curriculum_score"] / 10.0
)

# Feature 5: Student Proficiency Ratio
feature_df["student_proficiency_ratio"] = (
    feature_df["student_proficiency"] / 10.0
)

# Feature 6: Priority Score
feature_df["priority_score"] = (
    0.4 * feature_df["skill_gap"] +
    0.6 * feature_df["proficiency_gap"]
)

# Timestamp required by Feast
feature_df["event_timestamp"] = pd.Timestamp.now(tz="UTC")

# Display the engineered dataset
display(feature_df)

,skill_id,skill,curriculum_score,industry_score,student_proficiency,industry_demand,skill_gap,proficiency_gap,target,industry_demand_ratio,curriculum_coverage_ratio,student_proficiency_ratio,priority_score,event_timestamp
0,S001,Python,8,9,7,9,1,2,0,0.9,0.8,0.7,1.6,2026-08-18 06:20:55.153716+00:00
1,S002,JavaScript,7,9,5,9,2,4,1,0.9,0.7,0.5,3.2,2026-08-18 06:20:55.153716+00:00
2,S003,Java,8,8,6,8,0,2,0,0.8,0.8,0.6,1.2,2026-08-18 06:20:55.153716+00:00
3,S004,C++,8,7,6,7,-1,1,0,0.7,0.8,0.6,0.2,2026-08-18 06:20:55.153716+00:00
4,S005,SQL,9,9,7,9,0,2,0,0.9,0.9,0.7,1.2,2026-08-18 06:20:55.153716+00:00
5,S006,HTML_CSS,7,8,5,8,1,3,0,0.8,0.7,0.5,2.2,2026-08-18 06:20:55.153716+00:00
6,S007,React,5,8,4,8,3,4,1,0.8,0.5,0.4,3.6,2026-08-18 06:20:55.153716+00:00
7,S008,NodeJS,5,8,4,8,3,4,1,0.8,0.5,0.4,3.6,2026-08-18 06:20:55.153716+00:00
8,S009,MongoDB,5,7,4,7,2,3,1,0.7,0.5,0.4,2.6,2026-08-18 06:20:55.153716+00:00
9,S010,Git,6,9,6,9,3,3,1,0.9,0.6,0.6,3.0,2026-08-18 06:20:55.153716+00:00
10,S011,Docker,3,8,3,8,5,5,1,0.8,0.3,0.3,5.0,2026-08-18 06:20:55.153716+00:00
11,S012,Kubernetes,2,7,2,7,5,5,1,0.7,0.2,0.2,5.0,2026-08-18 06:20:55.153716+00:00
12,S013,AWS,3,8,3,8,5,5,1,0.8,0.3,0.3,5.0,2026-08-18 06:20:55.153716+00:00
13,S014,Machine_Learning,4,9,3,9,5,6,1,0.9,0.4,0.3,5.6,2026-08-18 06:20:55.153716+00:00
14,S015,Data_Structures,9,8,7,9,-1,2,0,0.9,0.9,0.7,0.8,2026-08-18 06:20:55.153716+00:00
15,S016,Algorithms,9,9,7,9,0,2,0,0.9,0.9,0.7,1.2,2026-08-18 06:20:55.153716+00:00
16,S017,Computer_Networks,7,8,5,8,1,3,0,0.8,0.7,0.5,2.2,2026-08-18 06:20:55.153716+00:00
17,S018,Cybersecurity,4,8,4,8,4,4,1,0.8,0.4,0.4,4.0,2026-08-18 06:20:55.153716+00:00
18,S019,Hadoop,3,7,3,7,4,4,1,0.7,0.3,0.3,4.0,2026-08-18 06:20:55.153716+00:00
19,S020,Spark,3,7,3,7,4,4,1,0.7,0.3,0.3,4.0,2026-08-18 06:20:55.153716+00:00

In [6]:
feature_path = f"{project_dir}/data/skill_features.parquet"

feature_df.to_parquet(
    feature_path,
    index=False
)

print(f"Feature dataset saved to:")
print(feature_path)

Feature dataset saved to:
/content/MLOps-Feast-SkillGap/data/skill_features.parquet

In [7]:
parquet_df = pd.read_parquet(feature_path)

print("Shape:", parquet_df.shape)
print("\nColumns:")
print(parquet_df.columns.tolist())

display(parquet_df)

Shape: (20, 14)

Columns:
['skill_id', 'skill', 'curriculum_score', 'industry_score', 'student_proficiency', 'industry_demand', 'skill_gap', 'proficiency_gap', 'target', 'industry_demand_ratio', 'curriculum_coverage_ratio', 'student_proficiency_ratio', 'priority_score', 'event_timestamp']

,skill_id,skill,curriculum_score,industry_score,student_proficiency,industry_demand,skill_gap,proficiency_gap,target,industry_demand_ratio,curriculum_coverage_ratio,student_proficiency_ratio,priority_score,event_timestamp
0,S001,Python,8,9,7,9,1,2,0,0.9,0.8,0.7,1.6,2026-08-18 06:20:55.153716+00:00
1,S002,JavaScript,7,9,5,9,2,4,1,0.9,0.7,0.5,3.2,2026-08-18 06:20:55.153716+00:00
2,S003,Java,8,8,6,8,0,2,0,0.8,0.8,0.6,1.2,2026-08-18 06:20:55.153716+00:00
3,S004,C++,8,7,6,7,-1,1,0,0.7,0.8,0.6,0.2,2026-08-18 06:20:55.153716+00:00
4,S005,SQL,9,9,7,9,0,2,0,0.9,0.9,0.7,1.2,2026-08-18 06:20:55.153716+00:00
5,S006,HTML_CSS,7,8,5,8,1,3,0,0.8,0.7,0.5,2.2,2026-08-18 06:20:55.153716+00:00
6,S007,React,5,8,4,8,3,4,1,0.8,0.5,0.4,3.6,2026-08-18 06:20:55.153716+00:00
7,S008,NodeJS,5,8,4,8,3,4,1,0.8,0.5,0.4,3.6,2026-08-18 06:20:55.153716+00:00
8,S009,MongoDB,5,7,4,7,2,3,1,0.7,0.5,0.4,2.6,2026-08-18 06:20:55.153716+00:00
9,S010,Git,6,9,6,9,3,3,1,0.9,0.6,0.6,3.0,2026-08-18 06:20:55.153716+00:00
10,S011,Docker,3,8,3,8,5,5,1,0.8,0.3,0.3,5.0,2026-08-18 06:20:55.153716+00:00
11,S012,Kubernetes,2,7,2,7,5,5,1,0.7,0.2,0.2,5.0,2026-08-18 06:20:55.153716+00:00
12,S013,AWS,3,8,3,8,5,5,1,0.8,0.3,0.3,5.0,2026-08-18 06:20:55.153716+00:00
13,S014,Machine_Learning,4,9,3,9,5,6,1,0.9,0.4,0.3,5.6,2026-08-18 06:20:55.153716+00:00
14,S015,Data_Structures,9,8,7,9,-1,2,0,0.9,0.9,0.7,0.8,2026-08-18 06:20:55.153716+00:00
15,S016,Algorithms,9,9,7,9,0,2,0,0.9,0.9,0.7,1.2,2026-08-18 06:20:55.153716+00:00
16,S017,Computer_Networks,7,8,5,8,1,3,0,0.8,0.7,0.5,2.2,2026-08-18 06:20:55.153716+00:00
17,S018,Cybersecurity,4,8,4,8,4,4,1,0.8,0.4,0.4,4.0,2026-08-18 06:20:55.153716+00:00
18,S019,Hadoop,3,7,3,7,4,4,1,0.7,0.3,0.3,4.0,2026-08-18 06:20:55.153716+00:00
19,S020,Spark,3,7,3,7,4,4,1,0.7,0.3,0.3,4.0,2026-08-18 06:20:55.153716+00:00

In [8]:
!pip install -q feast pyarrow scikit-learn pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 63.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 89.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 65.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [9]:
import feast

print("Feast version:", feast.__version__)

Feast version: 0.65.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
import os

feature_store_dir = f"{project_dir}/feature_store"

feature_store_yaml = """
project: skill_gap_project
provider: local
registry: data/registry.db
online_store:
    type: sqlite
    path: data/online_store.db
offline_store:
    type: file
"""

with open(f"{feature_store_dir}/feature_store.yaml", "w") as f:
    f.write(feature_store_yaml)

print("feature_store.yaml created successfully.")
print()
print(open(f"{feature_store_dir}/feature_store.yaml").read())

feature_store.yaml created successfully.


project: skill_gap_project
provider: local
registry: data/registry.db
online_store:
    type: sqlite
    path: data/online_store.db
offline_store:
    type: file

In [11]:
definitions_code = '''
from feast import Entity, FeatureView, Field
from feast.types import Float32, Int64
from feast.infra.offline_stores.file_source import FileSource
from datetime import timedelta


# --------------------------------------------------
# 1. Entity
# --------------------------------------------------

skill = Entity(
    name="skill_id",
    join_keys=["skill_id"],
    description="Unique identifier for a technical skill"
)


# --------------------------------------------------
# 2. Data Source
# --------------------------------------------------

skill_source = FileSource(
    path="../data/skill_features.parquet",
    timestamp_field="event_timestamp"
)


# --------------------------------------------------
# 3. Feature View
# --------------------------------------------------

skill_features = FeatureView(
    name="skill_features",
    entities=[skill],
    ttl=timedelta(days=365),
    schema=[
        Field(
            name="curriculum_score",
            dtype=Float32
        ),
        Field(
            name="industry_score",
            dtype=Float32
        ),
        Field(
            name="student_proficiency",
            dtype=Float32
        ),
        Field(
            name="industry_demand",
            dtype=Float32
        ),
        Field(
            name="skill_gap",
            dtype=Float32
        ),
        Field(
            name="proficiency_gap",
            dtype=Float32
        ),
        Field(
            name="industry_demand_ratio",
            dtype=Float32
        ),
        Field(
            name="curriculum_coverage_ratio",
            dtype=Float32
        ),
        Field(
            name="student_proficiency_ratio",
            dtype=Float32
        ),
        Field(
            name="priority_score",
            dtype=Float32
        ),
        Field(
            name="target",
            dtype=Int64
        )
    ],
    online=True,
    source=skill_source,
    tags={
        "project": "curriculum-industry-skill-gap"
    }
)
'''

definitions_path = f"{feature_store_dir}/definitions.py"

with open(definitions_path, "w") as f:
    f.write(definitions_code)

print("definitions.py created successfully.")

definitions.py created successfully.

In [12]:
print("Feature store files:")

for file in os.listdir(feature_store_dir):
    print(" -", file)

Feature store files:
 - feature_store.yaml
 - definitions.py

In [13]:
%cd /content/MLOps-Feast-SkillGap/feature_store

/content/MLOps-Feast-SkillGap/feature_store

In [14]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/MLOps-Feast-SkillGap/feature_store/definitions.py:12: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'skill_id'.
  skill = Entity(
No project found in the repository. Using project name skill_gap_project defined in feature_store.yaml
Applying changes for project skill_gap_project
Created project skill_gap_project
Created entity skill_id
Created feature view skill_features

Created sqlite table skill_gap_project_skill_features

In [15]:
print(open(f"{project_dir}/feature_store/feature_store.yaml").read())

project: skill_gap_project
provider: local
registry: data/registry.db
online_store:
    type: sqlite
    path: data/online_store.db
offline_store:
    type: file

In [16]:
print(open(f"{project_dir}/feature_store/definitions.py").read())

from feast import Entity, FeatureView, Field
from feast.types import Float32, Int64
from feast.infra.offline_stores.file_source import FileSource
from datetime import timedelta


# --------------------------------------------------
# 1. Entity
# --------------------------------------------------

skill = Entity(
    name="skill_id",
    join_keys=["skill_id"],
    description="Unique identifier for a technical skill"
)


# --------------------------------------------------
# 2. Data Source
# --------------------------------------------------

skill_source = FileSource(
    path="../data/skill_features.parquet",
    timestamp_field="event_timestamp"
)


# --------------------------------------------------
# 3. Feature View
# --------------------------------------------------

skill_features = FeatureView(
    name="skill_features",
    entities=[skill],
    ttl=timedelta(days=365),
    schema=[
        Field(
            name="curriculum_score",
            dtype=Float32
        ),
        Field(
            name="industry_score",
            dtype=Float32
        ),
        Field(
            name="student_proficiency",
            dtype=Float32
        ),
        Field(
            name="industry_demand",
            dtype=Float32
        ),
        Field(
            name="skill_gap",
            dtype=Float32
        ),
        Field(
            name="proficiency_gap",
            dtype=Float32
        ),
        Field(
            name="industry_demand_ratio",
            dtype=Float32
        ),
        Field(
            name="curriculum_coverage_ratio",
            dtype=Float32
        ),
        Field(
            name="student_proficiency_ratio",
            dtype=Float32
        ),
        Field(
            name="priority_score",
            dtype=Float32
        ),
        Field(
            name="target",
            dtype=Int64
        )
    ],
    online=True,
    source=skill_source,
    tags={
        "project": "curriculum-industry-skill-gap"
    }
)

In [17]:
%cd /content/MLOps-Feast-SkillGap/feature_store
!feast apply

/content/MLOps-Feast-SkillGap/feature_store
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/MLOps-Feast-SkillGap/feature_store/definitions.py:12: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'skill_id'.
  skill = Entity(
No project found in the repository. Using project name skill_gap_project defined in feature_store.yaml
Applying changes for project skill_gap_project
No changes to registry
No changes to infrastructure

In [18]:
definitions_code = '''
from feast import Entity, FeatureView, Field, ValueType
from feast.types import Float32, Int64
from feast.infra.offline_stores.file_source import FileSource
from datetime import timedelta


# --------------------------------------------------
# 1. Entity
# --------------------------------------------------

skill = Entity(
    name="skill_id",
    join_keys=["skill_id"],
    value_type=ValueType.STRING,
    description="Unique identifier for a technical skill"
)


# --------------------------------------------------
# 2. Data Source
# --------------------------------------------------

skill_source = FileSource(
    path="../data/skill_features.parquet",
    timestamp_field="event_timestamp"
)


# --------------------------------------------------
# 3. Feature View
# --------------------------------------------------

skill_features = FeatureView(
    name="skill_features",
    entities=[skill],
    ttl=timedelta(days=365),
    schema=[
        Field(name="curriculum_score", dtype=Float32),
        Field(name="industry_score", dtype=Float32),
        Field(name="student_proficiency", dtype=Float32),
        Field(name="industry_demand", dtype=Float32),
        Field(name="skill_gap", dtype=Float32),
        Field(name="proficiency_gap", dtype=Float32),
        Field(name="industry_demand_ratio", dtype=Float32),
        Field(name="curriculum_coverage_ratio", dtype=Float32),
        Field(name="student_proficiency_ratio", dtype=Float32),
        Field(name="priority_score", dtype=Float32),
        Field(name="target", dtype=Int64)
    ],
    online=True,
    source=skill_source,
    tags={
        "project": "curriculum-industry-skill-gap"
    }
)
'''

with open(definitions_path, "w") as f:
    f.write(definitions_code)

print("definitions.py updated successfully.")

definitions.py updated successfully.

In [19]:
print(open(definitions_path).read())

from feast import Entity, FeatureView, Field, ValueType
from feast.types import Float32, Int64
from feast.infra.offline_stores.file_source import FileSource
from datetime import timedelta


# --------------------------------------------------
# 1. Entity
# --------------------------------------------------

skill = Entity(
    name="skill_id",
    join_keys=["skill_id"],
    value_type=ValueType.STRING,
    description="Unique identifier for a technical skill"
)


# --------------------------------------------------
# 2. Data Source
# --------------------------------------------------

skill_source = FileSource(
    path="../data/skill_features.parquet",
    timestamp_field="event_timestamp"
)


# --------------------------------------------------
# 3. Feature View
# --------------------------------------------------

skill_features = FeatureView(
    name="skill_features",
    entities=[skill],
    ttl=timedelta(days=365),
    schema=[
        Field(name="curriculum_score", dtype=Float32),
        Field(name="industry_score", dtype=Float32),
        Field(name="student_proficiency", dtype=Float32),
        Field(name="industry_demand", dtype=Float32),
        Field(name="skill_gap", dtype=Float32),
        Field(name="proficiency_gap", dtype=Float32),
        Field(name="industry_demand_ratio", dtype=Float32),
        Field(name="curriculum_coverage_ratio", dtype=Float32),
        Field(name="student_proficiency_ratio", dtype=Float32),
        Field(name="priority_score", dtype=Float32),
        Field(name="target", dtype=Int64)
    ],
    online=True,
    source=skill_source,
    tags={
        "project": "curriculum-industry-skill-gap"
    }
)

In [20]:
from feast import Entity, FeatureView, Field, ValueType

In [21]:
value_type=ValueType.STRING

In [22]:
%cd /content/MLOps-Feast-SkillGap/feature_store
!feast apply

/content/MLOps-Feast-SkillGap/feature_store
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
No project found in the repository. Using project name skill_gap_project defined in feature_store.yaml
Applying changes for project skill_gap_project
Updated entity skill_id
	value_type: 0 -> 2

No changes to infrastructure

In [23]:
%cd /content/MLOps-Feast-SkillGap

/content/MLOps-Feast-SkillGap

In [24]:
historical_code = '''
import pandas as pd
from feast import FeatureStore

# ---------------------------------------------
# Load Feast feature store
# ---------------------------------------------

store = FeatureStore(
    repo_path="/content/MLOps-Feast-SkillGap/feature_store"
)

# ---------------------------------------------
# Create entity dataframe
# ---------------------------------------------

entity_df = pd.read_parquet(
    "/content/MLOps-Feast-SkillGap/data/skill_features.parquet"
)

# Feast requires event_timestamp
entity_df = entity_df[
    ["skill_id", "event_timestamp", "target"]
]

# ---------------------------------------------
# Historical feature retrieval
# ---------------------------------------------

training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "skill_features:curriculum_score",
        "skill_features:industry_score",
        "skill_features:student_proficiency",
        "skill_features:industry_demand",
        "skill_features:skill_gap",
        "skill_features:proficiency_gap",
        "skill_features:industry_demand_ratio",
        "skill_features:curriculum_coverage_ratio",
        "skill_features:student_proficiency_ratio",
        "skill_features:priority_score"
    ]
).to_df()

# ---------------------------------------------
# Save result
# ---------------------------------------------

output_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/historical_features.csv"
)

training_df.to_csv(output_path, index=False)

print("Historical feature retrieval completed.")
print()
print("Shape:", training_df.shape)
print()
print("Columns:")
print(training_df.columns.tolist())
print()
print("Historical Features:")
print(training_df)

print()
print("Saved to:")
print(output_path)
'''

historical_path = f"{project_dir}/src/historical_retrieval.py"

with open(historical_path, "w") as f:
    f.write(historical_code)

print("historical_retrieval.py created.")

historical_retrieval.py created.

In [25]:
!python src/historical_retrieval.py

Historical feature retrieval completed.

Shape: (20, 13)

Columns:
['skill_id', 'event_timestamp', 'target', 'curriculum_score', 'industry_score', 'student_proficiency', 'industry_demand', 'skill_gap', 'proficiency_gap', 'industry_demand_ratio', 'curriculum_coverage_ratio', 'student_proficiency_ratio', 'priority_score']

Historical Features:
   skill_id  ... priority_score
0      S001  ...            1.6
1      S018  ...            4.0
2      S017  ...            2.2
3      S016  ...            1.2
4      S015  ...            0.8
5      S014  ...            5.6
6      S013  ...            5.0
7      S012  ...            5.0
8      S011  ...            5.0
9      S010  ...            3.0
10     S009  ...            2.6
11     S008  ...            3.6
12     S007  ...            3.6
13     S006  ...            2.2
14     S005  ...            1.2
15     S004  ...            0.2
16     S003  ...            1.2
17     S002  ...            3.2
18     S019  ...            4.0
19     S020  ...            4.0

[20 rows x 13 columns]

Saved to:
/content/MLOps-Feast-SkillGap/outputs/historical_features.csv

In [26]:
training_code = '''
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# --------------------------------------------------
# Load historical features retrieved through Feast
# --------------------------------------------------

data_path = "/content/MLOps-Feast-SkillGap/outputs/historical_features.csv"

df = pd.read_csv(data_path)

# --------------------------------------------------
# Select Feast features
# --------------------------------------------------

feature_columns = [
    "curriculum_score",
    "industry_score",
    "student_proficiency",
    "industry_demand",
    "skill_gap",
    "proficiency_gap",
    "industry_demand_ratio",
    "curriculum_coverage_ratio",
    "student_proficiency_ratio",
    "priority_score"
]

X = df[feature_columns]
y = df["target"]

# --------------------------------------------------
# Split dataset
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

# --------------------------------------------------
# Train model
# --------------------------------------------------

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# --------------------------------------------------
# Evaluate model
# --------------------------------------------------

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print()
print("Model Accuracy:", round(accuracy * 100, 2), "%")
print()

print("Classification Report:")
print(classification_report(y_test, y_pred))

# --------------------------------------------------
# Save model accuracy
# --------------------------------------------------

accuracy_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/model_accuracy.txt"
)

with open(accuracy_path, "w") as f:
    f.write(f"Model Accuracy: {accuracy * 100:.2f}%\\n")

print("Accuracy saved to:")
print(accuracy_path)
'''

training_path = f"{project_dir}/src/train_model.py"

with open(training_path, "w") as f:
    f.write(training_code)

print("train_model.py created successfully.")

train_model.py created successfully.

In [28]:
!python src/train_model.py

python3: can't open file '/content/MLOps-Feast-SkillGap/feature_store/src/train_model.py': [Errno 2] No such file or directory

In [27]:
%cd /content/MLOps-Feast-SkillGap/feature_store

print(open("feature_store.yaml").read())

/content/MLOps-Feast-SkillGap/feature_store

project: skill_gap_project
provider: local
registry: data/registry.db
online_store:
    type: sqlite
    path: data/online_store.db
offline_store:
    type: file

In [29]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME            ENTITIES      TYPE         ENABLED    STATE
skill_features  {'skill_id'}  FeatureView  Yes        STATE_UNSPECIFIED

In [30]:
from datetime import datetime, timezone

end_time = datetime.now(timezone.utc)

print("Materializing up to:", end_time)

Materializing up to: 2026-08-18 06:23:40.016923+00:00

In [31]:
!feast materialize-incremental "{end_time.isoformat()}"

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views to 2026-08-18 06:23:40+00:00 into the sqlite online store.

skill_features from 2025-08-18 06:24:22+00:00 to 2026-08-18 06:23:40+00:00:

In [33]:
import os

online_store_path = (
    "/content/MLOps-Feast-SkillGap/"
    "feature_store/data/online_store.db"
)

if os.path.exists(online_store_path):
    print("Online store created successfully.")
    print("Path:", online_store_path)
else:
    print("Online store was not created.")

Online store created successfully.
Path: /content/MLOps-Feast-SkillGap/feature_store/data/online_store.db

In [34]:
from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/MLOps-Feast-SkillGap/feature_store"
)

print("Feast FeatureStore loaded successfully.")

Feast FeatureStore loaded successfully.

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [35]:
online_features = store.get_online_features(
    features=[
        "skill_features:curriculum_score",
        "skill_features:industry_score",
        "skill_features:student_proficiency",
        "skill_features:industry_demand",
        "skill_features:skill_gap",
        "skill_features:proficiency_gap",
        "skill_features:industry_demand_ratio",
        "skill_features:curriculum_coverage_ratio",
        "skill_features:student_proficiency_ratio",
        "skill_features:priority_score"
    ],
    entity_rows=[
        {"skill_id": "S014"}
    ]
).to_dict()

print(online_features)

{'skill_id': ['S014'], 'curriculum_coverage_ratio': [0.4000000059604645], 'proficiency_gap': [6.0], 'student_proficiency': [3.0], 'industry_demand_ratio': [0.8999999761581421], 'industry_demand': [9.0], 'priority_score': [5.599999904632568], 'curriculum_score': [4.0], 'industry_score': [9.0], 'student_proficiency_ratio': [0.30000001192092896], 'skill_gap': [5.0]}

In [36]:
online_code = '''
import json
from feast import FeatureStore

# --------------------------------------------------
# Load Feast Feature Store
# --------------------------------------------------

store = FeatureStore(
    repo_path="/content/MLOps-Feast-SkillGap/feature_store"
)

# --------------------------------------------------
# Retrieve features for S014
# --------------------------------------------------

skill_id = "S014"

online_features = store.get_online_features(
    features=[
        "skill_features:curriculum_score",
        "skill_features:industry_score",
        "skill_features:student_proficiency",
        "skill_features:industry_demand",
        "skill_features:skill_gap",
        "skill_features:proficiency_gap",
        "skill_features:industry_demand_ratio",
        "skill_features:curriculum_coverage_ratio",
        "skill_features:student_proficiency_ratio",
        "skill_features:priority_score"
    ],
    entity_rows=[
        {"skill_id": skill_id}
    ]
).to_dict()

# --------------------------------------------------
# Save online feature output
# --------------------------------------------------

output_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/online_features.json"
)

with open(output_path, "w") as f:
    json.dump(online_features, f, indent=4)

# --------------------------------------------------
# Display result
# --------------------------------------------------

print("Online feature retrieval completed.")
print()
print("Skill ID:", skill_id)
print()

for key, value in online_features.items():
    print(f"{key}: {value}")

print()
print("Saved to:")
print(output_path)
'''

online_path = f"{project_dir}/src/online_retrieval.py"

with open(online_path, "w") as f:
    f.write(online_code)

print("online_retrieval.py created successfully.")

online_retrieval.py created successfully.

In [37]:
%cd /content/MLOps-Feast-SkillGap

!python src/online_retrieval.py

/content/MLOps-Feast-SkillGap
Online feature retrieval completed.

Skill ID: S014

skill_id: ['S014']
curriculum_score: [4.0]
industry_demand_ratio: [0.8999999761581421]
industry_score: [9.0]
priority_score: [5.599999904632568]
student_proficiency_ratio: [0.30000001192092896]
student_proficiency: [3.0]
proficiency_gap: [6.0]
curriculum_coverage_ratio: [0.4000000059604645]
skill_gap: [5.0]
industry_demand: [9.0]

Saved to:
/content/MLOps-Feast-SkillGap/outputs/online_features.json

In [38]:
training_code = '''
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# --------------------------------------------------
# Load historical features retrieved through Feast
# --------------------------------------------------

data_path = "/content/MLOps-Feast-SkillGap/outputs/historical_features.csv"

df = pd.read_csv(data_path)

# --------------------------------------------------
# Feature columns
# --------------------------------------------------

feature_columns = [
    "curriculum_score",
    "industry_score",
    "student_proficiency",
    "industry_demand",
    "skill_gap",
    "proficiency_gap",
    "industry_demand_ratio",
    "curriculum_coverage_ratio",
    "student_proficiency_ratio",
    "priority_score"
]

X = df[feature_columns]
y = df["target"]

# --------------------------------------------------
# Train/test split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# --------------------------------------------------
# Train Random Forest
# --------------------------------------------------

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# --------------------------------------------------
# Evaluation
# --------------------------------------------------

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print()
print("Model Accuracy:", round(accuracy * 100, 2), "%")
print()
print("Classification Report:")
print(classification_report(y_test, y_pred))

# --------------------------------------------------
# Save model
# --------------------------------------------------

model_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/skill_gap_model.joblib"
)

joblib.dump(model, model_path)

# --------------------------------------------------
# Save accuracy
# --------------------------------------------------

accuracy_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/model_accuracy.txt"
)

with open(accuracy_path, "w") as f:
    f.write(f"Model Accuracy: {accuracy * 100:.2f}%\\n")

print("Model saved to:")
print(model_path)
'''

with open(training_path, "w") as f:
    f.write(training_code)

print("train_model.py updated successfully.")

train_model.py updated successfully.

In [39]:
!python src/train_model.py

Training samples: 14
Testing samples: 6

Model Accuracy: 83.33 %

Classification Report:
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.75      0.86         4

    accuracy                           0.83         6
   macro avg       0.83      0.88      0.83         6
weighted avg       0.89      0.83      0.84         6

Model saved to:
/content/MLOps-Feast-SkillGap/outputs/skill_gap_model.joblib

In [40]:
prediction_code = '''
import pandas as pd
import joblib

from feast import FeatureStore

# --------------------------------------------------
# Load trained model
# --------------------------------------------------

model_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/skill_gap_model.joblib"
)

model = joblib.load(model_path)

# --------------------------------------------------
# Load Feast Feature Store
# --------------------------------------------------

store = FeatureStore(
    repo_path="/content/MLOps-Feast-SkillGap/feature_store"
)

# --------------------------------------------------
# Skill for prediction
# --------------------------------------------------

skill_id = "S014"

# --------------------------------------------------
# Retrieve latest features from Feast
# --------------------------------------------------

online_features = store.get_online_features(
    features=[
        "skill_features:curriculum_score",
        "skill_features:industry_score",
        "skill_features:student_proficiency",
        "skill_features:industry_demand",
        "skill_features:skill_gap",
        "skill_features:proficiency_gap",
        "skill_features:industry_demand_ratio",
        "skill_features:curriculum_coverage_ratio",
        "skill_features:student_proficiency_ratio",
        "skill_features:priority_score"
    ],
    entity_rows=[
        {"skill_id": skill_id}
    ]
).to_dict()

# --------------------------------------------------
# Convert Feast output to model input
# --------------------------------------------------

feature_columns = [
    "curriculum_score",
    "industry_score",
    "student_proficiency",
    "industry_demand",
    "skill_gap",
    "proficiency_gap",
    "industry_demand_ratio",
    "curriculum_coverage_ratio",
    "student_proficiency_ratio",
    "priority_score"
]

input_data = {
    column: [online_features[column][0]]
    for column in feature_columns
}

X_new = pd.DataFrame(input_data)

# --------------------------------------------------
# Generate prediction
# --------------------------------------------------

prediction = model.predict(X_new)[0]

if prediction == 1:
    result = "High-priority skill gap"
else:
    result = "Low/Moderate-priority skill gap"

# --------------------------------------------------
# Display result
# --------------------------------------------------

print("Final Prediction")
print("----------------")
print("Skill ID:", skill_id)
print("Prediction:", int(prediction))
print("Result:", result)

# --------------------------------------------------
# Save prediction
# --------------------------------------------------

output_path = (
    "/content/MLOps-Feast-SkillGap/"
    "outputs/prediction.txt"
)

with open(output_path, "w") as f:
    f.write(f"Skill ID: {skill_id}\\n")
    f.write(f"Prediction: {int(prediction)}\\n")
    f.write(f"Result: {result}\\n")

print()
print("Prediction saved to:")
print(output_path)
'''

prediction_path = f"{project_dir}/src/final_prediction.py"

with open(prediction_path, "w") as f:
    f.write(prediction_code)

print("final_prediction.py created successfully.")

final_prediction.py created successfully.

In [41]:
%cd /content/MLOps-Feast-SkillGap

!python src/final_prediction.py

/content/MLOps-Feast-SkillGap
Final Prediction
----------------
Skill ID: S014
Prediction: 1
Result: High-priority skill gap

Prediction saved to:
/content/MLOps-Feast-SkillGap/outputs/prediction.txt